---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Dashboard"
subtitle: "Andronics"
# logo: "logo.png"
icon: "fas fa-server" # Optional icon
columns: 3

header: true
# footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

defaults:
  layout: columns # columns, list
  colorTheme: dark # auto, light, dark


# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Some pre-defined tag styles. reference these using <<: *{NAME} inside an item definition; For Example, <<: *Apps
tags: 
  Favourite: &Favourite
    - tag: "Favourite"
      tagstyle: "is-medium is-primary"
  CI: &CI
    - tag: "CI"
      tagstyle: "is-medium is-success"
  Apps: &Apps
    - tag: "App"
      tagstyle: "is-medium is-info"

# # Optional message
# message:
#   #url: https://b4bz.io
#   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#   title: "Demo !"
#   icon: "fa fa-grin"
#   content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  - name: "another page!"
    icon: "fas fa-file-alt"
    url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Financial"
    icon: "fas fa-piggy-bank"
    items:
      - name: "Clearscore"
        logo: "assets/logos/clearscore.png"
        subtitle: "Portal for Halifax Personal accounts"
        <<: *Apps
        tag: "bank"
        url: "https://www.halifax-online.co.uk/personal/logon/"
      - name: "Halifax"
        logo: "assets/logos/halifax.png"
        subtitle: "Management portal for Halifax bank account"
        tag: "bank"
        url: "https://www.halifax-online.co.uk/personal/logon/"
      - name: "PayPal"
        logo: "assets/logos/paypal.png"
        subtitle: "Management portal for PayPal account"
        tag: "bank"
        url: "https://www.paypal.com"
      - name: "Santander"
        logo: "assets/logos/santander.png"
        subtitle: "Management portal for Santander bank account"
        tag: "bank"
        url: "https://retail.santander.co.uk/olb/app/logon/access/#/logon"
  - name: "PVR"
    icon: "fas fa-photo-video"
    items:
      - name: "Bazarr"
        logo: "assets/logos/bazarr.png"
        subtitle: "Subtitle PVR"
        tag: "download"
        class: "pvr"
        url: "http://bazarr.andronics.io"
      - name: "Deluge"
        logo: "assets/logos/deluge.svg"
        subtitle: "Cross Platform BitTorrent Client"
        tag: "download"
        url: "http://deluge.andronics.io"
      - name: "Emby"
        logo: "assets/logos/emby.png"
        subtitle: "Media Server"
        tag: "download"
        url: "http://emby.andronics.io"
      - name: "Jackett"
        logo: "assets/logos/jackett.png"
        subtitle: "Indexer for Torrent & Usenet"
        tag: "indexer"
        url: "http://jackett.andronics.io"
      - name: "Lidarr"
        logo: "assets/logos/lidarr.svg"
        subtitle: "Music PVR for BitTorrent & Usenet"
        tag: "pvr"
        type: "Lidarr"
        apikey: "6a92cbe344bc4d8ea3f55a6e6a06655c"
        url: "http://lidarr.andronics.io/"
      - name: "Prowlarr"
        logo: "assets/logos/prowlarr.png"
        subtitle: "Manage trackers for Sonarr, Radarr, Readarr, Liadarr &"
        tag: "pvr"
        url: "http://prowlarr.andronics.io/"
      - name: "Radarr"
        logo: "assets/logos/radarr.png"
        subtitle: "Automatically downloads Movies"
        tag: "pvr"
        type: "Radarr"
        apikey: "1f53552237404bf0a2a849758d1e857f"
        url: "http://radarr.andronics.io/"
      - name: "Readarr"
        logo: "assets/logos/readarr.png"
        subtitle: "Automatically downloads eBooks"
        tag: "pvr"
        url: "http://readarr.andronics.io/"
      - name: "Sonarr"
        logo: "assets/logos/sonarr.svg"
        subtitle: "Automatically downloads TV Shows"
        tag: "pvr"
        type: "Sonarr"
        apikey: "875739e72461402cbbf8842b8b00ff27"
        url: "http://sonarr.andronics.io/"